name: Bug 汇报
description: 游戏无法正常进行 / 功能无法正常使用
title: "[BUG] "
labels: "» Bug"
body:
- type: markdown
  attributes:
    value: "请在确认当前地图版本为**最新**版本时再提交"
- type: textarea
  id: "yml-1"
  attributes:
    label: 描述
    description: "尽可能**详细**地描述发生了什么"
  validations:
    required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 重现
    description: "描述触发该Bug的具体步骤，如果你不知道那就写你干了什么"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 附件
    description: "如果可以的话，请提供该Bug的游戏内截图"
    placeholder: "把截图粘贴到这里，或者直接把文件拖进来"