name: 游戏优化
description: 对游戏有什么具体建议想要提出来
title: "[游戏优化] "
labels: "» 优化"
body:
- type: textarea
  id: "yml-1"
  attributes:
    label: 建议内容
    description: "告诉我们想要修改什么成什么样子"
  validations:
    required: true
- type: textarea
  id: "yml-2"
  attributes:
    label: 优化内容
    description: "描述一下这个修改可以对游戏的哪些方面产生良性影响"
  validations:
    required: true
- type: textarea
  id: "yml-3"
  attributes:
    label: 附件
    description: "如果可以的话，给一个例子让我们看看是极好的"
    placeholder: "把截图粘贴到这里，或者直接把文件拖进来"